language: haxe

haxe:
  - "development"
  - "3.2.1"

os:
  - linux
  - osx

sudo: required
dist: trusty
addons:
  apt:
    packages:
      - php5-cli

install:
  - yes | haxelib install all
  # minject 2.0.0-rc.1 is required... can be removed once minject 2.0.0 loses its rc tag
  - yes | haxelib install minject 2.0.0-rc.1 && haxelib set minject 2.0.0-rc.1
  # https://github.com/ufront/erazor/commit/b2a110587ea42b0874f8dc4f947078d4d334e1bd
  - haxelib git erazor https://github.com/ufront/erazor.git
  - haxelib list
  # print php version
  - php -v
  # remove Xdebug to avoid:
  # PHP Fatal error:  Maximum function nesting level of '256' reached
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      phpenv config-rm xdebug.ini;
    fi;

script:
  - haxe test-neko.hxml && neko build/neko_test.n
  - haxe test-php.hxml && php build/php_test.php
  - haxe test-js-browser.hxml